thriftServices:
  - http: POST /echo
    requestParser: sgw.parser.EchoServiceEchoParams
    responseGenerator: sgw.parser.EchoServiceEchoResult
    service: echoservice
    method: echo
    clazz: examples.thrift_service.EchoService
  - http: POST /echo2
    requestParser: sgw.parser.EchoServiceEchoParams
    responseGenerator: sgw.parser.EchoServiceEchoResult
    service: echoservice
    method: echo
    clazz: examples.thrift_service.EchoService

