thriftServices:
  - service: echoservice
    method: echo
    http: POST /echo
    convertor: demo.parser.EchoConvertor
    clazz: demo.gen.echo.service.EchoService
  - service: echoplusservice
    method: echo
    http: POST /echoplus
    convertor: demo.parser.EchoplusConvertor
    clazz: demo.gen.echoplus.service.EchoplusService
  - http: POST /echoplus/{id}
    convertor: demo.parser.EchoplusIdConvertor
    service: echoplusservice
    method: echo
    clazz: demo.gen.echoplus.service.EchoplusService
