thriftServices:
  - http: POST /echo
    requestParser: demo.parser.EchoReqParser
    responseGenerator: demo.parser.EchoServiceEchoResult
    service: echoservice
    method: echo
    clazz: gen.echo.service.EchoService
  - http: POST /echoplus
    requestParser: demo.parser.EchoplusReqParser
    responseGenerator: demo.parser.EchoplusRspGen
    service: echoplusservice
    method: echo
    clazz: gen.echoplus.service.EchoplusService

